name: "Build for VxWorks"

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

env:
  REV: ${{ github.run_id }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        os: [
          "self-hosted-build-lin-1",
        ]
    runs-on: ${{ matrix.os }}
    env:
      PPC: powerpc-wrs-vxworks
      PPC_LIB: ${{ github.workspace }}/powerpc-wrs-vxworks/14.0.0/powerpc-wrs-vxworks/lib/msoft-float
      PPC_BIN: ${{ github.workspace }}/powerpc-wrs-vxworks/14.0.0/bin
      X86: x86_64-linux-gnu
      X86_BIN: ${{ github.workspace }}/x86_64-linux-gnu/14.0.0/bin
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
        with:
          gh-token: ${{ secrets.CC_BUILD_TOKEN }}
          target: "vxworks-ppc"
      # TODO: cache the toolchain
      - name: Download gccgo-vxworks
        uses: spideroak-inc/action-download-artifact@v2.26.0
        with:
          workflow: main.yml
          workflow_conclusion: success
          check_artifacts:  true
          search_artifacts: true
          branch: libtool
          name: ${{ env.PPC }}.tar.gz
          repo: spideroak-inc/gccgo-vxworks
          github_token: ${{ secrets.CC_BUILD_TOKEN }}
      - name: Extract gccgo-vxworks toolchain
        run: |
          tar -xzf ${{ env.PPC }}.tar.gz
      - name: Build
        env:
          TARGET_AR: ${{ env.PPC_BIN }}/${{ env.PPC }}-ar
          TARGET_CC: ${{ env.PPC_BIN }}/${{ env.PPC }}-gcc
          TARGET_CXX: ${{ env.PPC_BIN }}/${{ env.PPC }}-g++
          TARGET_LD_LIBRARY_PATH: ${{ env.PPC_LIB }}
          TARGET_NM: ${{ env.PPC_BIN }}/${{ env.PPC }}-nm
          TARGET_RANLIB: ${{ env.PPC_BIN }}/${{ env.PPC }}-ranlib
          TARGET_STRIP: ${{ env.PPC_BIN }}/${{ env.PPC }}-strip
        run: cargo build --verbose --release
